version: '3'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    container_name: 'sample-web-store-backend-app'
    env_file:
      - .env.common
    ports:
      - 8080:8080
    volumes:
      - ./:/app:cached
      - /app/.git
    tty: true
    stdin_open: true

  db:
    image: postgres:10
    container_name: 'sample-web-store-backend-db'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'development'
    ports:
      - '5432:5432'
    volumes:
      - sample-web-store-backend-db:/var/lib/postgresql/data
      - ./pg_init/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

volumes:
  sample-web-store-backend-db:
